var Ucai=this.Ucai||{};Ucai.Resource=Ucai.Resource||{};Ucai.error=function(a,j){j=j||Error;throw new j(a);};Ucai.global=this;
(function(a){var j=Array.prototype,g=Object.prototype,d=j.slice,e=g.toString,h=g.hasOwnProperty,c=j.forEach,f=j.map,l=j.reduce,m=j.reduceRight,q=j.filter,w=j.every,u=j.some,v=j.indexOf,x=j.lastIndexOf,j=Array.isArray,g=Object.keys,t=Object.create;a.log=function(){if(a.__debug)if("console"in window&&"log"in window.console){var b=arguments.length;1==b?window.console.log(arguments[0]):2==b&&window.console.log(arguments[0],arguments[1])}else window.opera&&window.opera.postError&&window.opera.postError.apply(window.opera,
arguments)};var r={};a.forEach=function(b,k,n){if(null!=b)if(c&&b.forEach===c)b.forEach(k,n);else if(a.isNumber(b.length))for(var s=0,f=b.length;s<f&&k.call(n,b[s],s,b)!=r;s++);else for(s in b)if(h.call(b,s)&&k.call(n,b[s],s,b)===r)break};a.map=function(b,k,n){var s=[];if(null==b)return s;if(f&&b.map===f)return b.map(k,n);a.forEach(b,function(b,a,c){s[s.length]=k.call(n,b,a,c)});return s};a.reduce=function(b,k,n,c){var f=void 0!==n;null==b&&(b=[]);if(l&&b.reduce===l)return c&&(k=a.bind(k,c)),f?b.reduce(k,
n):b.reduce(k);a.forEach(b,function(b,a,e){!f&&0===a?(n=b,f=!0):n=k.call(c,n,b,a,e)});if(!f)throw new TypeError("Reduce of empty array with no initial value");return n};a.reduceRight=function(b,k,n,c){null==b&&(b=[]);if(m&&b.reduceRight===m)return c&&(k=a.bind(k,c)),void 0!==n?b.reduceRight(k,n):b.reduceRight(k);b=(a.isArray(b)?b.slice():a.toArray(b)).reverse();return a.reduce(b,k,n,c)};a.detect=function(b,k,n){var c;a.some(b,function(b,a,f){if(k.call(n,b,a,f))return c=b,!0});return c};a.filter=function(b,
k,n){var c=[];if(null==b)return c;if(q&&b.filter===q)return b.filter(k,n);a.forEach(b,function(b,a,f){k.call(n,b,a,f)&&(c[c.length]=b)});return c};a.every=function(b,k,n){var c=!0;if(null==b)return c;if(w&&b.every===w)return b.every(k,n);a.forEach(b,function(b,a,f){if(!(c=c&&k.call(n,b,a,f)))return r});return c};a.some=function(b,k,n){k||(k=a.identity);var c=!1;if(null==b)return c;if(u&&b.some===u)return b.some(k,n);a.forEach(b,function(b,a,f){if(k.call(n,b,a,f))return c=!0,r});return c};a.contains=
function(b,k){var c=!1;if(null==b)return c;if(v&&b.indexOf===v)return-1!=b.indexOf(k);a.some(b,function(b){if(c=b===k)return!0});return c};a.pluck=function(b,k){return a.map(b,function(b){return b[k]})};a.sortBy=function(b,k,c){return a.pluck(a.map(b,function(b,a,f){return{value:b,criteria:k.call(c,b,a,f)}}).sort(function(b,a){var k=b.criteria,c=a.criteria;return k<c?-1:k>c?1:0}),"value")};a.sortedIndex=function(b,k,c){c||(c=a.identity);for(var f=0,e=b.length;f<e;){var d=f+e>>1;c(b[d])<c(k)?f=d+1:
e=d}return f};a.toArray=function(b){return!b?[]:b.toArray?b.toArray():a.isArray(b)?b:a.isArguments(b)?d.call(b):a.values(b)};a.last=function(b){var a=b.length;return 0<a?b[a-1]:void 0};a.compact=function(b){return a.filter(b,function(b){return!!b})};a.flatten=function(b){return a.reduce(b,function(b,c){if(a.isArray(c))return b.concat(a.flatten(c));b[b.length]=c;return b},[])};a.without=function(b,k){var c=d.call(arguments,1);return a.filter(b,function(b){return!a.contains(c,b)})};a.unique=function(b,
k){return a.reduce(b,function(b,c,f){if(0==f||(!0===k?a.last(b)!=c:!a.contains(b,c)))b[b.length]=c;return b},[])};a.intersect=function(b){var c=d.call(arguments,1);return a.filter(a.unique(b),function(b){return a.every(c,function(c){return 0<=a.indexOf(c,b)})})};a.indexOf=function(b,c,f){if(null==b)return-1;var e;if(f)return f=a.sortedIndex(b,c),b[f]===c?f:-1;if(v&&b.indexOf===v)return b.indexOf(c);f=0;for(e=b.length;f<e;f++)if(b[f]===c)return f;return-1};a.lastIndexOf=function(b,a){if(null==b)return-1;
if(x&&b.lastIndexOf===x)return b.lastIndexOf(a);for(var c=b.length;c--;)if(b[c]===a)return c;return-1};a.bind=function(b,c){var f=Array.prototype.slice.call(arguments,2);return function(){c=c||(this==a.global?!1:this);var e=f.concat(Array.prototype.slice.call(arguments));if("string"==typeof b&&c[b])c[b].apply(c,e);else{if(a.isFunction(b))return b.apply(c,e);a.log("not function",b)}}};a.methodize=function(b,a){return a?function(){return b.apply(null,[this[a]].concat([].slice.call(arguments)))}:function(){return b.apply(null,
[this].concat([].slice.call(arguments)))}};a.extend=function(b,c){var f=function(){};f.prototype=c.prototype;var e=b.prototype;b.prototype=new f;b.$super=c;a.mix(b.prototype,e,!0);return b};a.create=t||function(b,c){var f=function(b){b&&a.mix(this,b,!0)};f.prototype=b;return new f(c)};a.delay=function(b,a){var c=d.call(arguments,2);return setTimeout(function(){return b.apply(b,c)},a)};a.defer=function(b){return a.delay.apply(a,[b,1].concat(d.call(arguments,1)))};a.keys=g||function(b){if(b!==Object(b))throw new TypeError("Invalid object");
var a=[],c;for(c in b)h.call(b,c)&&(a[a.length]=c);return a};a.values=function(b){return a.map(b,a.identity)};a.methods=function(b){return a.filter(a.keys(b),function(c){return a.isFunction(b[c])}).sort()};a.mix=function(b){a.forEach(d.call(arguments,1),function(a){for(var c in a)void 0!==a[c]&&(b[c]=a[c])});return b};a.clone=function(b){return a.isArray(b)?b.slice():a.mix({},b)};a.isEmpty=function(b){if(a.isArray(b)||a.isString(b))return 0===b.length;for(var c in b)if(h.call(b,c))return!1;return!0};
a.isElement=function(b){return!!(b&&1==b.nodeType)};a.isArray=j||function(b){return"[object Array]"===e.call(b)};a.isFunction=function(b){return!(!b||!b.constructor||!b.call||!b.apply)};a.isArguments="[object Arguments]"==e.call(arguments)?function(b){return"[object Arguments]"==e.call(b)}:function(b){return!(!b||!h.call(b,"callee"))};a.isString=function(b){return!!(""===b||b&&b.charCodeAt&&b.substr)};a.isNumber=function(b){return!!(0===b||b&&b.toExponential&&b.toFixed)};a.isNaN=function(b){return b!==
b};a.isBoolean=function(b){return!0===b||!1===b};a.isDate=function(b){return!(!b||!b.getTimezoneOffset||!b.setUTCFullYear)};a.isRegExp=function(b){return!(!b||!b.test||!b.exec||!(b.ignoreCase||!1===b.ignoreCase))};a.isNull=function(b){return null===b};a.isUndefined=function(b){return void 0===b};a.trim=function(b){return b.replace(/^[\s\xa0\u3000]+|[\u3000\xa0\s]+$/g,"")};a.byteLen=function(b){return b.replace(/[^\x00-\xff]/g,"--").length};a.subByte=function(b,c,f){if(a.byteLen(b)<=c)return b;f=f||
"";c-=a.byteLen(f);return b.substr(0,c).replace(/([^\x00-\xff])/g,"$1 ").substr(0,c).replace(/[^\x00-\xff]$/,"").replace(/([^\x00-\xff]) /g,"$1")+f};a.encode4JS=function(b){return b.replace(/\\/g,"\\u005C").replace(/"/g,"\\u0022").replace(/'/g,"\\u0027").replace(/\//g,"\\u002F").replace(/\r/g,"\\u000A").replace(/\n/g,"\\u000D").replace(/\t/g,"\\u0009")};a.encode4HTTP=function(b){return b.replace(/[\u0000-\u0020\u0080-\u00ff\s"'#\/\|\\%<>\[\]\{\}\^~;\?\:@=&]/,function(b){return encodeURIComponent(b)})};
a.encode4Html=function(b){return b.replace(/&(?!\w+;|#\d+;|#x[\da-f]+;)/gi,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};a.decodefromHtml=function(b){return b.replace(/&lt;/g,"<").replace(/&amp;/g,"&").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&#x2F;/g,"/")};a.encode4HtmlValue=function(b){return a.encode4Html(b).replace(/"/g,"&quot;").replace(/'/g,"&#039;")};a.stripTags=function(b){return b.replace(/<[^>]*>/gi,
"")};a.formatDate=function(b,a){a=a||"yyyy-MM-dd";var c=b.getFullYear(),f={M:b.getMonth()+1,d:b.getDate(),h:b.getHours(),m:b.getMinutes(),s:b.getSeconds()};a=a.replace(/(y+)/ig,function(b,a){var f=Math.min(4,a.length);return(c+"").substr(4-f)});for(var e in f)a=a.replace(RegExp("("+e+"+)","g"),function(b,a){return 10>f[e]&&1<a.length?"0"+f[e]:f[e]});return a};a.identity=function(b){return b};var p=0;a.uniqueId=function(b){var a=p++;return b?b+a:a}})(Ucai);
(function(a,j){var g;a.isSupportTouch=function(){if(g===j){a.log("detecting touch support");for(var d=["touchstart","touchmove","touchend"],e=!0,h=document.createElement("div"),c=0,f=d.length;c<f;c++){var l="on"+d[c],m=l in h;m||(h.setAttribute(l,"return;"),m="function"==typeof h[l]);if(!m){e=!1;break}}g=e}return g}})(Ucai);
Ucai.Browser=function(){var a=window.navigator,j=a.userAgent.toLowerCase(),g={platform:a.platform};j.replace(/(msie|webkit|gecko|presto|opera|safari|firefox|chrome|maxthon)[ \/]([\d.]+)/ig,function(a,e,h){a=e.toLowerCase();g[a]=h});g.opera&&j.replace(/opera.*version\/([\d.]+)/,function(a,e){g.opera=e});g.msie&&(g.ie=g.msie,a=parseInt(g.msie,10),g["ie"+a]=!0);g.safari&&g.chrome&&(g.safari=!1);return g}();if(Ucai.Browser.ie)try{document.execCommand("BackgroundImageCache",!1,!0)}catch(e$$12){}
function onDetectFocus(){Ucai.windowFocused=!0}function onDetectBlur(){Ucai.windowFocused=!1}Ucai.Browser.ie?(document.attachEvent("onfocusin",onDetectFocus),document.attachEvent("onfocusout",onDetectBlur)):(window.addEventListener("focus",onDetectFocus,!1),window.addEventListener("blur",onDetectBlur,!1));
(function(a){var j=function(){this.__callbacks__={}};a.mix(j.prototype,{on:function(g,d,e){e&&(d=a.bind(d,e));var h=this.__callbacks__[g];if(h&&!0===h.fired)d.apply(e,h.args);else return this.__callbacks__[g]=this.__callbacks__[g]||[],this.__callbacks__[g].push(d),[g,d]},un:function(g){var d=g[0],e=g[1];if(d in this.__callbacks__){var h=this.__callbacks__[d];a.forEach(h,function(a,f){e==a&&(h[f]=null)})}},once:function(a,d,e){var h=this,c=this.on(a,function(){d.apply(e,arguments);h.un(c)})},fire:function(g){if(g in
this.__callbacks__){var d=this.__callbacks__[g],e=Array.prototype.slice.call(arguments,1);a.forEach(d,function(a){return"function"!=typeof a?null:a.apply(null,e)})}},fireReady:function(g){var d=this.__callbacks__[g];d||(d=this.__callbacks__[g]=[]);var e=Array.prototype.slice.call(arguments,1);a.forEach(d,function(a){return"function"!=typeof a?null:a.apply(null,e)});d.fired=!0;d.args=e}});a.Pubsub=j;a.mix(a,new j)})(Ucai);
(function(a,j,g){function d(c,f,e){if(0<=a.indexOf(f,c))throw Error("Module:"+c+" could't depends on itself!");this.id=c;this.dependancy=f;this.factory=e}var e={},h={};d.createRequire=function(c,f){function l(g,l){if(!l&&-1==a.indexOf(c,g))throw Error(g+" counld't be required in "+f+", as you not declared to depend it ");var h=e[g];if(!h)return null;if(!h.exports){var j=h.factory;if(a.isFunction(j)){if(h.exports={},j=j(d.createRequire(h.dependancy,h.id),h.exports,h))h.exports=j}else void 0!==j&&(h.exports=
j)}return h.exports}l.async=function(c,f,e){c=a.isString(c)?[c]:c;var h=a.unique(c),h=d.getDependancy(h);d.load(h);d.wait(h,function(){for(var a=[],d=0,h=c.length;d<h;d++)a.push(l(c[d],!0));f.apply(e||g,a)})};return l};d.getDependancy=function(a){return j.getDependancy(a)};d.load=function(c){c=a.isString(c)?[c]:c;a.forEach(c,function(a){j.loadModule(a)})};d.defined=function(){return e};d.waiting=function(){return a.keys(h)};d.check=function(c,f){c=a.trim(c);0==c.length||e[c]?f&&f():(h[c]=!0,a.on("Module:"+
c+":Ready",f))};d.wait=function(a,f){a=[].concat(a);if(0<a.length){var e=a.shift();d.check(e,function(){d.wait(a,f)})}else f&&f()};g.define=a.define=function(c,f,g){if(2>arguments.length)throw Error("module has invalid parameters");if(!a.isString(c))throw Error("module must have a ID");if(a.isFunction(f))g=f,f=[];else if(!a.isArray(f)){var j=f;g=function(){return j};f=[]}if(e[c])a.fire("Ucai:resource:conflict");else{var q=a.unique(f),q=d.getDependancy(q);d.wait(q,function(){var j=new d(c,f,g);e[c]=
j;try{delete h[c]}catch(q){}a.fire("Module:"+c+":Ready")})}};g.Module=a.Module=d})(Ucai,Ucai.Resource,this);
(function(a,j){var g={},d={},e="http://{_STCHOST_}/",h=/\.js$/i,c={},f={},l=[],m=[],q;j.addResourceMap=function(b){a.mix(g,b)};j.getResourceMap=function(b){return g[b]};j.addResourceDepends=function(b){a.mix(d,b)};j.setBasePath=function(b){e=b};j.getDependancy=function(b,c){var f=[];b=a.isString(b)?[b]:b;c=c||[];a.forEach(b,function(b){b=b.replace(h,"");c=c.concat(f);-1==a.indexOf(c,b)&&f.unshift(b);if(b=d[b+".js"])b=j.getDependancy(b,c),b.length&&f.unshift.apply(f,b)});return f};var w=/^\/+|\/+$/ig;
j.loadModule=function(b){b=b.replace(w,"");h.test(b)||(b+=".js");(b=g[b])&&j.loadJS(e+b)};j.canonicalURI=function(b){/^\/\/\/?/.test(b)&&(b=location.protocol+b);return b};var u=function(){for(var b=document.getElementsByTagName("link"),a=b.length,f;a;)if(f=b[--a],("stylesheet"==f.rel||"text/css"==f.type)&&f.href)c[j.canonicalURI(f.href)]=!0;b=document.getElementsByTagName("script");for(a=b.length;a;)if(f=b[--a],(!f.type||"text/javascript"==f.type)&&f.src)c[j.canonicalURI(f.src)]=!0;u=function(){}},
v=function(b){var e,d;delete f[b];c[b]=!0;for(d=0;d<l.length;d++)e=l[d],delete e.resources[b],a.isEmpty(e.resources)&&(e.callback&&e.callback(),l.splice(d--,1))},x=function(){for(var b=document.styleSheets,c=b.length;c--;){var f=b[c],e=!1;if(a.Browser.firefox)try{f.cssRules&&(e=!0)}catch(d){if("SecurityError"===d.name||"NS_ERROR_DOM_SECURITY_ERR"===d.name)e=!0}else e=!0;if(e&&(f=f.ownerNode||f.owningElement,e=m.length,f))for(;e--;)f==m[e]&&(v(m[e]["data-href"]),m.splice(e,1))}m.length||(clearInterval(q),
q=null)},t=function(b){var c=document.createElement("script"),f=function(){c.onload=c.onerror=c.onreadystatechange=null;v(b)};a.mix(c,{type:"text/javascript",src:b,async:!0});c.onload=c.onerror=f;c.onreadystatechange=function(){var b=this.readyState;("complete"==b||"loaded"==b)&&f()};document.getElementsByTagName("head")[0].appendChild(c)},r=function(b){var c=document.createElement("link");a.mix(c,{type:"text/css",rel:"stylesheet",href:b,"data-href":b});document.getElementsByTagName("head")[0].appendChild(c);
c.attachEvent?c.onload=function(){v(b)}:(m.push(c),q||(q=setInterval(x,20)))},p=function(b,e){var d={},h;u();b=a.isArray(b)?b:[b];for(var g=0,q=b.length;g<q;g++)h=j.canonicalURI(b[g]),d[h]=!0,c[h]?setTimeout(a.bind(v,null,h),0):f[h]||(f[h]=!0,-1<h.indexOf(".css")?r(h):t(h));e&&l.push({resources:d,callback:e})};j.loadJS=function(b,a){p(b,a)};j.loadCSS=function(b,a){p(b,a)};j.loadIMG=function(b,a){var c=new Image;a="function"===typeof a?a:function(){};c.onload=function(){c.onload=null;a.call(null,c)};
"complete"==c.readyState&&a.call(null,c);c.src=b};j.loadStyle=function(b){var a=document.createElement("style");(document.getElementsByTagName("head")[0]||document.body).appendChild(a);a.styleSheet?a.styleSheet.cssText=b:a.appendChild(document.createTextNode(b))}})(Ucai,Ucai.Resource);
(function(a){var j=!1,g=!1;a.ready=function(c){if(j)c();else a.on("Onload:DomContentLoaded",c)};a.load=function(c){if(g)c();else a.on("Onload:Loaded",c)};var d=function(){j||(j=!0,a.fire("Onload:DomContentLoaded"))},e;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,!1);d()}:document.attachEvent&&(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),d())});var h=function(){if(!j){try{document.documentElement.doScroll("left")}catch(a){setTimeout(h,
1);return}document.detachEvent("onreadystatechange",e);d()}};var c=a.global,f=c.document,l=function(){j||(j=!0,d());g||(g=!0,a.fire("Onload:Loaded"))};if("complete"==f.readyState)setTimeout(d,0);else if(f.addEventListener)f.addEventListener("DOMContentLoaded",e,!1),c.addEventListener("load",l,!1);else if(f.attachEvent){f.attachEvent("onreadystatechange",e);c.attachEvent("onload",l);l=!1;try{l=null==c.frameElement}catch(m){}f.documentElement.doScroll&&l&&h()}})(Ucai);
(function(a,j){function g(c,d,h){if(e[c])throw a.fire("Ucai:resource:conflict"),Error("App:"+c+" has defined");e[c]=this;this.id=c;this.requiredModList=d;this.execBeforeDomready=h}var d="require getContainer".split(/\s+/ig),e={};a.mix(g.prototype,{define:function(c){var e=a.unique(this.requiredModList),g=j.getDependancy(e),q=this,w=function(){a.fire("App:"+q.id+":Ready",q)};j.wait(g,function(){var g=j.createRequire(e,q.id);a.isFunction(c)&&(c=c.call({},g));if(c){var m,x,t;m=0;for(x=d.length;m<x;m++)if(t=
d[m],c[t])throw Error(t+" is a reserve method or property");c.require=g;g=c.require("core/jQuery");q.__jQuery__=g;if(!(c.container&&0==g(c.container).length)){var r;m=c;var p;m.container||(m.container=document.body);p=g(m.container);if(!p.length||1<p.length)p=g(document.body);m.container=p;m.getContainer=function(){return p};r=p;if(c.events){var b=c;a.map(b.events,function(c,f){var e=f.match(h),d=e[1],e=e[2],g=a.bind(b[c],b);e?r.delegate(e,d,a.bind(b[c],b)):r.bind(d,g)})}a.isFunction(c.main)?q.execBeforeDomready?
(c.main(),w()):a.ready(function(){c.main();w()}):w()}}})}});var h=/^([\w\.]+)(?:\s+(.*))?$/,c=0;a.App=function(f,e,d){var h;if((h=arguments[0])&&a.isString(h)){if("A"!=a.last(h.split(/\//ig)).charAt(0))throw Error(h+" is a invalid name for a App");}else h="__APP__"+c++;var j=a.detect(arguments,function(c){return a.isArray(c)})||[],u;u=a.last(arguments);u=a.isBoolean(u)?u:!1;return new g(h,j,u)};a.use=function(c,e,d){a.isFunction(c)?(e=c,c=[]):a.isString(c)&&(c=[c]);return a.App("App_"+this.uniqueId(),
c,d).define(e)};a.App.get=function(a){return e[a]||null}})(Ucai,Ucai.Module);
(function(a){var j=a.mix,g=a.indexOf,d=a.CustEvent=function(a,d,c){this.target=a;this.type=d;j(this,c||{})};j(d.prototype,{target:null,currentTarget:null,type:null,returnValue:void 0,preventDefault:function(){this.returnValue=!1}});a.CustEventTargetH={on:function(e,d,c){e=e.__custListeners&&e.__custListeners[d]||a.error("unknown event type",TypeError);if(-1<g(e,c))return!1;e.push(c);return!0},once:function(e,d,c){e.__custListeners&&e.__custListeners[d]||a.error("unknown event type",TypeError);var f=
$.proxy(function(g){c.call(e,g);a.CustEventTargetH.un(e,d,f)},this);a.CustEventTargetH.on(e,d,f);return!0},un:function(e,d,c){e=e.__custListeners&&e.__custListeners[d]||a.error("unknown event type",TypeError);if(c){c=g(e,c);if(0>c)return!1;e.splice(c,1)}else e.length=0;return!0},fire:function(e,g,c){g instanceof d?(c=j(g,c),g=g.type):c=new d(e,g,c);var f=e.__custListeners&&e.__custListeners[g]||a.error("unknown event type",TypeError);"*"!=g&&(f=f.concat(e.__custListeners["*"]||[]));c.returnValue=
void 0;c.currentTarget=e;if((e=c.currentTarget)&&e["on"+c.type])var l=e["on"+c.type].call(e,c);for(g=0;g<f.length;g++)f[g].call(e,c);return!1!==c.returnValue||!1===l&&void 0===c.returnValue},createEvents:function(a,d){d=d||[];"string"==typeof d&&(d=d.split(","));var c=a.__custListeners;c||(c=a.__custListeners={});for(var f=0;f<d.length;f++)c[d[f]]=c[d[f]]||[];c["*"]=c["*"]||[];return a}}})(Ucai);
(function(a){var j=function(){};a.Helper={methodize:function(g,d){var e=new j,h;for(h in g)"function"==typeof g[h]&&!/^_/.test(h)&&(e[h]=a.methodize(g[h],d));return e}}})(Ucai);(function(a){var j=a.mix,g=a.CustEventTarget=function(){this.__custListeners={}},d=a.Helper.methodize(a.CustEventTargetH,null,{on:"operator",un:"operator"});j(g.prototype,d);a.CustEvent.createEvents=g.createEvents=function(e,d){a.CustEventTargetH.createEvents(e,d);return j(e,g.prototype)}})(Ucai);(function(a){a.Env={}})(Ucai);
(function(a){a.onbeforeunload=function(a){if(a)if("function"==typeof window.onbeforeunload){var g=window.onbeforeunload;window.onbeforeunload=function(){var d=a.apply(null,arguments),e=g.apply(null,arguments);return e?e:d}}else window.onbeforeunload=a}})(Ucai);
(function(a){a.Performance={timing:{}};var j=window.performance||window.msPerformance||window.webkitPerformance||window.mozPerformance;j&&j.timing?a.Performance.timing=j.timing:(a.Performance.timing.responseStart=a.global.pageStart,a.ready(function(){a.Performance.timing.domContentLoadedEventStart=(new Date).getTime()}),a.load(function(){a.Performance.timing.loadEventStart=(new Date).getTime()}))})(Ucai);
(function(a){var j=function(a,c){for(c=c.toUpperCase();a&&a.nodeName!=c;)a=a.parentNode;return a},g=function(c,f,e){var d;b:if("hasAttribute"in c)d=c.getAttribute("data-app");else{if("getAttributeNode"in c&&(d=c.getAttributeNode("data-app"))){d=d.value;break b}d=void 0}var g;if(g=d)if(g=d.length)g=d,!("App"in a)||!a.App.get(g)?(a.log(g,"not ready"),g=!1):g=!0,g=!g;d=g?d:!1;var j;if(d)return a.once("App:"+d+":Ready",function(a){a.__jQuery__(e||c)[f]()}),!1;if("click"==f&&(d=c.getAttribute("data-ajax"))&&
d.length){j=c.getAttribute("data-ajax-url")||c.href;switch(d){case "dialog-post":case "dialog":a.Module.createRequire().async("core/dialog/Dialog",function(a){a.load(j,c)});break;case "request-post":case "request":a.Module.createRequire().async("core/ajax/Request",function(a){a.load(j,c)});break;default:return}return!1}},d=function(a){a=j(a,"FORM")||a;return g(a,"submit")},e,h=document.createElement("div"),c="onsubmit"in h;c||(h.setAttribute("onsubmit","return;"),c="function"===typeof h.onsubmit);
e=c;var h=a.global.document.documentElement,f=null;h.onclick=function(a){a=a||window.event;f=a.target||a.srcElement;if(!e){var c=f.type;if("submit"==c||"image"==c)return d(f)}if((c=f.href)&&!/#$/.test(c))if(c=a.altKey||a.ctrlKey||a.metaKey||a.shiftKey,a.which&&1!=a.which||c)return;a=f;c=j(a,"A")||a;return g(c,"click",a)};e||(h.onkeypress=function(a){a=a||window.event;f=a.target||a.srcElement;var c=f.type;if(("text"==c||"password"==c)&&13==a.keyCode)return d(f)});e&&(h.onsubmit=function(a){a=a||window.event;
return d(a.target||a.srcElement)})})(Ucai);
(function(){function a(){return this.init.apply(this,arguments)}var j={version:"0.1.3",templateSettings:{evaluate:/\{\{([\s\S]+?)\}\}/g,interpolate:/\{\{=([\s\S]+?)\}\}/g,encode:/\{\{!([\s\S]+?)\}\}/g,defines:/\{\{#([\s\S]+?)\}\}/g,varname:"it",strip:!0},template:function(a,d){d=d||j.templateSettings;var e=("var out='"+(d.strip?a.replace(/\s*<!\[CDATA\[\s*|\s*\]\]>\s*|[\r\n\t]|(\/\*[\s\S]*?\*\/)/g,""):a).replace(d.defines,function(a,d){return eval(d.replace(/[\r\t\n]/g," "))}).replace(/\\/g,"\\\\").replace(/'/g,
"\\'").replace(d.interpolate,function(a,d){return"';out+="+d.replace(/\\'/g,"'").replace(/\\\\/g,"\\").replace(/[\r\t\n]/g," ")+";out+='"}).replace(d.encode,function(a,d){return"';out+=("+d.replace(/\\'/g,"'").replace(/\\\\/g,"\\").replace(/[\r\t\n]/g," ")+").toString().replace(/&(?!\\w+;)/g, '&#38;').split('<').join('&#60;').split('>').join('&#62;').split('\"').join('&#34;').split(\"'\").join('&#39;').split('/').join('&#x2F;');out+='"}).replace(d.evaluate,function(a,d){return"';"+d.replace(/\\'/g,
"'").replace(/\\\\/g,"\\").replace(/[\r\t\n]/g," ")+"out+='"})+"';return out;").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,"\\r").split("out+='';").join("").split('var out="";out+=').join("var out=");try{return new Function(d.varname,e)}catch(h){throw"undefined"!==typeof console&&console.log("Could not create a template function: "+e),h;}}};a.prototype={init:function(a){a=a||{};this.path=a.path||"/";this.domain=a.domain||"";this.expires=a.expires||31536E6;this.secure=a.secure||""},set:function(a,
d){var e=new Date;"number"==typeof this.expires&&e.setTime(e.getTime()+this.expires);document.cookie=a+"="+escape(d)+";expires="+e.toGMTString()+";path="+this.path+(""==this.domain?"":"; domain="+this.domain)+(this.secure?"; secure":"")},get:function(a){var d;return(d=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(d[2]):""},remove:function(a){var d=this.expires;this.expires=-31536E6;this.set(a,"");this.expires=d}};a.set=function(g,d,e){(new a(e)).set(g,d)};a.get=function(g,d){return(new a(d)).get(g)};
a.remove=function(g,d){(new a(d)).remove(g)};window.doT=j;window.Cookie=a})();
(function(){function a(a){return 10>a?"0"+a:a}function j(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var c=l[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function g(a,d){var e,h,l,t,r=c,p,b=d[a];b&&("object"===typeof b&&"function"===typeof b.toJSON)&&(b=b.toJSON(a));"function"===typeof m&&(b=m.call(d,a,b));switch(typeof b){case "string":return j(b);case "number":return isFinite(b)?String(b):"null";case "boolean":case "null":return String(b);
case "object":if(!b)return"null";c+=f;p=[];if("[object Array]"===Object.prototype.toString.apply(b)){t=b.length;for(e=0;e<t;e+=1)p[e]=g(e,b)||"null";l=0===p.length?"[]":c?"[\n"+c+p.join(",\n"+c)+"\n"+r+"]":"["+p.join(",")+"]";c=r;return l}if(m&&"object"===typeof m){t=m.length;for(e=0;e<t;e+=1)h=m[e],"string"===typeof h&&(l=g(h,b))&&p.push(j(h)+(c?": ":":")+l)}else for(h in b)Object.prototype.hasOwnProperty.call(b,h)&&(l=g(h,b))&&p.push(j(h)+(c?": ":":")+l);l=0===p.length?"{}":c?"{\n"+c+p.join(",\n"+
c)+"\n"+r+"}":"{"+p.join(",")+"}";c=r;return l}}if("object"!=typeof window.JSON){var d=window.JSON={};"use strict";"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=
/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,f,l={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;"function"!==typeof d.stringify&&(d.stringify=function(a,d,e){var h;f=c="";if("number"===typeof e)for(h=0;h<e;h+=1)f+=" ";else"string"===typeof e&&(f=e);if((m=d)&&"function"!==typeof d&&
("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return g("",{"":a})});"function"!==typeof d.parse&&(d.parse=function(a,c){function d(a,e){var f,g,b=a[e];if(b&&"object"===typeof b)for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(g=d(b,f),void 0!==g?b[f]=g:delete b[f]);return c.call(a,e,b)}var f;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),"function"===typeof c?d({"":f},""):f;throw new SyntaxError("JSON.parse");});Object.prototype.toJSONString||(Object.prototype.toJSONString=function(a){return d.stringify(this,a)},Object.prototype.parseJSON=function(a){return d.parse(this,a)})}})();